ALTER TABLE "Compra" ADD COLUMN "moneda" TEXT NOT NULL DEFAULT 'ARS';
ALTER TABLE "Cuota" ADD COLUMN "moneda" TEXT NOT NULL DEFAULT 'ARS';
ALTER TABLE "Resumen" ADD COLUMN "totalConsumosUSDInformado" DECIMAL(10,2);
ALTER TABLE "Resumen" ADD COLUMN "saldoUSDInformado" DECIMAL(10,2);
