ALTER TYPE "TipoCargoResumen" ADD VALUE 'IVA_INTERESES';
ALTER TYPE "TipoCargoResumen" ADD VALUE 'IVA_COMISIONES';
ALTER TYPE "TipoCargoResumen" ADD VALUE 'IVA_IMPUESTOS';
ALTER TYPE "TipoCargoResumen" ADD VALUE 'IMPUESTO_SELLO';
